title: Vaelion of Ocris
url: https://vaelionofocris.com
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
collections:
  posts:
    output: true
markdown: kramdown
highlighter: rouge
